# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

# Data Cleaning

### Load and Inspect Data

In [5]:
import pandas as pd

In [6]:
import numpy as np

# LABEVENTS

In [7]:
labs = pd.read_csv(r"C:\Users\SAKSHI PATIL\PycharmProjects\JupyterProject\data\raw\MediScan_database\LABEVENTS.csv")
labs

,row_id,subject_id,hadm_id,itemid,charttime,value,valuenum,valueuom,flag
0,6244563,10006,NaN,50868,2164-09-24 20:21:00,19,19.00,mEq/L,NaN
1,6244564,10006,NaN,50882,2164-09-24 20:21:00,27,27.00,mEq/L,NaN
2,6244565,10006,NaN,50893,2164-09-24 20:21:00,10.0,10.00,mg/dL,NaN
3,6244566,10006,NaN,50902,2164-09-24 20:21:00,97,97.00,mEq/L,NaN
4,6244567,10006,NaN,50912,2164-09-24 20:21:00,7.0,7.00,mg/dL,abnormal
...,...,...,...,...,...,...,...,...,...
76069,20452679,44228,103379.0,51250,2170-12-24 04:09:00,88,88.00,fL,NaN
76070,20452680,44228,103379.0,51265,2170-12-24 04:09:00,595,595.00,K/uL,abnormal
76071,20452681,44228,103379.0,51277,2170-12-24 04:09:00,14.5,14.50,%,NaN
76072,20452682,44228,103379.0,51279,2170-12-24 04:09:00,2.76,2.76,m/uL,abnormal
76073,20452683,44228,103379.0,51301,2170-12-24 04:09:00,16.9,16.90,K/uL,abnormal

### Drop unnecessary columns

In [34]:
labs = labs[['subject_id','hadm_id','itemid','charttime','valuenum','valueuom','flag']]

### Handle missing hadm_id

In [35]:
labs = labs.dropna(subset=['hadm_id'])
labs

,subject_id,hadm_id,itemid,charttime,valuenum,valueuom,flag
633,10006,142345.0,50813,2164-10-23 17:33:00,4.40,mmol/L,abnormal
634,10006,142345.0,50861,2164-10-23 17:38:00,9.00,IU/L,NaN
635,10006,142345.0,50862,2164-10-23 17:38:00,3.40,g/dL,NaN
636,10006,142345.0,50863,2164-10-23 17:38:00,167.00,IU/L,abnormal
637,10006,142345.0,50868,2164-10-23 17:38:00,20.00,mEq/L,NaN
...,...,...,...,...,...,...,...
76069,44228,103379.0,51250,2170-12-24 04:09:00,88.00,fL,NaN
76070,44228,103379.0,51265,2170-12-24 04:09:00,595.00,K/uL,abnormal
76071,44228,103379.0,51277,2170-12-24 04:09:00,14.50,NaN,NaN
76072,44228,103379.0,51279,2170-12-24 04:09:00,2.76,m/uL,abnormal
76073,44228,103379.0,51301,2170-12-24 04:09:00,16.90,K/uL,abnormal

### Map itemid → test names
Right now you only see numeric itemid. You should join with D_LABITEMS.csv to get human‑readable labels

In [36]:
d_labitems = pd.read_csv(r"C:\Users\SAKSHI PATIL\PycharmProjects\JupyterProject\data\raw\MediScan_database\D_LABITEMS.csv")[['itemid','label']]
labs = labs.merge(d_labitems, on='itemid', how='left')

### Flag abnormal values clearly

In [37]:
labs['flag'] = labs['flag'].fillna("normal")
labs

,subject_id,hadm_id,itemid,charttime,valuenum,valueuom,flag,label
0,10006,142345.0,50813,2164-10-23 17:33:00,4.40,mmol/L,abnormal,Lactate
1,10006,142345.0,50861,2164-10-23 17:38:00,9.00,IU/L,normal,Alanine Aminotransferase (ALT)
2,10006,142345.0,50862,2164-10-23 17:38:00,3.40,g/dL,normal,Albumin
3,10006,142345.0,50863,2164-10-23 17:38:00,167.00,IU/L,abnormal,Alkaline Phosphatase
4,10006,142345.0,50868,2164-10-23 17:38:00,20.00,mEq/L,normal,Anion Gap
...,...,...,...,...,...,...,...,...
61807,44228,103379.0,51250,2170-12-24 04:09:00,88.00,fL,normal,MCV
61808,44228,103379.0,51265,2170-12-24 04:09:00,595.00,K/uL,abnormal,Platelet Count
61809,44228,103379.0,51277,2170-12-24 04:09:00,14.50,NaN,normal,RDW
61810,44228,103379.0,51279,2170-12-24 04:09:00,2.76,m/uL,abnormal,Red Blood Cells
61811,44228,103379.0,51301,2170-12-24 04:09:00,16.90,K/uL,abnormal,White Blood Cells

### Drop unused columns

In [38]:
labs = labs[['subject_id','hadm_id','charttime','label','valuenum','valueuom','flag']]

### Handle missing hadm_id
Some labs don’t have an admission ID. Since you’re building admission‑level reports, drop those rows

In [39]:
labs = labs.dropna(subset=['hadm_id'])

### Standardize units
Sometimes the same test appears in different units (e.g., glucose in mg/dL vs mmol/L). You may want to normalize units for consistency.

In [40]:
# Example: convert mmol/L to mg/dL for glucose
labs.loc[(labs['label']=='Glucose') & (labs['valueuom']=='mmol/L'), 'valuenum'] *= 18
labs.loc[(labs['label']=='Glucose') & (labs['valueuom']=='mmol/L'), 'valueuom'] = 'mg/dL'

### Flag abnormal values programmatically

In [42]:
labs['interpretation'] = labs.apply(
    lambda row: 'High' if row['label']=='Glucose' and row['valuenum']>125 else
                'Low' if row['label']=='Hemoglobin' and row['valuenum']<12 else
                row['flag'], axis=1
)
labs

,subject_id,hadm_id,charttime,label,valuenum,valueuom,flag,interpretation
0,10006,142345.0,2164-10-23 17:33:00,Lactate,4.40,mmol/L,abnormal,abnormal
1,10006,142345.0,2164-10-23 17:38:00,Alanine Aminotransferase (ALT),9.00,IU/L,normal,normal
2,10006,142345.0,2164-10-23 17:38:00,Albumin,3.40,g/dL,normal,normal
3,10006,142345.0,2164-10-23 17:38:00,Alkaline Phosphatase,167.00,IU/L,abnormal,abnormal
4,10006,142345.0,2164-10-23 17:38:00,Anion Gap,20.00,mEq/L,normal,normal
...,...,...,...,...,...,...,...,...
61807,44228,103379.0,2170-12-24 04:09:00,MCV,88.00,fL,normal,normal
61808,44228,103379.0,2170-12-24 04:09:00,Platelet Count,595.00,K/uL,abnormal,abnormal
61809,44228,103379.0,2170-12-24 04:09:00,RDW,14.50,NaN,normal,normal
61810,44228,103379.0,2170-12-24 04:09:00,Red Blood Cells,2.76,m/uL,abnormal,abnormal
61811,44228,103379.0,2170-12-24 04:09:00,White Blood Cells,16.90,K/uL,abnormal,abnormal

### Drop redundant columns

In [43]:
labs = labs[['subject_id','hadm_id','charttime','label','valuenum','valueuom','flag','interpretation']]

### Handle missing hadm_id
For admission‑level grouping, drop rows without hadm_id

In [44]:
labs = labs.dropna(subset=['hadm_id'])

### Fix unit issues
Some rows have NaN in valueuom (e.g., RDW). You can fill with "Unknown Unit"

In [46]:
labs['valueuom'] = labs['valueuom'].fillna("Unknown Unit")

Saving cleaned lab dataset

In [88]:
labs.columns

Index(['subject_id', 'hadm_id', 'charttime', 'label', 'valuenum', 'valueuom',
       'flag', 'interpretation'],
      dtype='str')

In [89]:
labs_clean = labs[['subject_id','hadm_id','charttime','label','valuenum','valueuom','interpretation']]

In [90]:
labs_clean.to_csv("data/interim/labs_clean.csv", index=False)

In [92]:
import os
print(os.listdir("data/interim"))

['labs_clean.csv']

### Group labs per admission
Now you’re ready to group them into lists for final_dataset

In [48]:
labs_grouped = (
    labs.groupby(['subject_id','hadm_id'])[['charttime','label','valuenum','valueuom','flag','interpretation']]
    .apply(lambda x: x.to_dict('records'))
    .reset_index()
    .rename(columns={0:'labs'})
)
labs_grouped

     subject_id   hadm_id                                               labs
0         10006  142345.0  [{'charttime': '2164-10-23 17:33:00', 'label':...
1         10011  105331.0  [{'charttime': '2126-08-15 01:30:00', 'label':...
2         10013  165520.0  [{'charttime': '2125-10-04 23:59:00', 'label':...
3         10017  199207.0  [{'charttime': '2149-05-26 09:26:00', 'label':...
4         10019  177759.0  [{'charttime': '2163-05-14 19:53:00', 'label':...
..          ...       ...                                                ...
124       44083  198330.0  [{'charttime': '2112-05-28 12:30:00', 'label':...
125       44154  174245.0  [{'charttime': '2178-05-14 16:45:00', 'label':...
126       44212  163189.0  [{'charttime': '2123-11-24 14:40:00', 'label':...
127       44222  192189.0  [{'charttime': '2180-07-19 04:15:00', 'label':...
128       44228  103379.0  [{'charttime': '2170-12-15 02:37:00', 'label':...

[129 rows x 3 columns]

### Column naming consistency
Make sure the grouped column is explicitly named labs (not 0 or unnamed). You already did this, but double‑check

In [49]:
labs_grouped.rename(columns={0:'labs'}, inplace=True)

### Diagnoses & Prescriptions
Do the same grouping for diagnoses and prescriptions

In [50]:
diagnoses_grouped = (
    diagnoses.groupby(['subject_id','hadm_id'])['short_title']
    .apply(list)
    .reset_index()
    .rename(columns={'short_title':'diagnoses'})
)

prescriptions_grouped = (
    prescriptions.groupby(['subject_id','hadm_id'])[['drug','dose_val_rx','dose_unit_rx','route']]
    .apply(lambda x: x.to_dict('records'))
    .reset_index()
    .rename(columns={0:'prescriptions'})
)

### Final Merge
Merge all three grouped datasets

In [52]:
final_dataset = (
    labs_grouped
    .merge(diagnoses_grouped, on=['subject_id','hadm_id'], how='left')
    .merge(prescriptions_grouped, on=['subject_id','hadm_id'], how='left')
)
final_dataset

,subject_id,hadm_id,labs,diagnoses,prescriptions
0,10006,142345.0,"[{'charttime': '2164-10-23 17:33:00', 'label':...","[[[Sepsis, React-oth vasc dev/graft, nan, Hyp ...","[{'drug': 'Sodium Chloride 0.9% Flush', 'dose..."
1,10011,105331.0,"[{'charttime': '2126-08-15 01:30:00', 'label':...","[[[Acute necrosis of liver, Hpt B acte wo cm w...",NaN
2,10013,165520.0,"[{'charttime': '2125-10-04 23:59:00', 'label':...","[[[Septicemia NOS, Subendo infarct, initial, C...","[{'drug': 'Furosemide', 'dose_val_rx': '20', '..."
3,10017,199207.0,"[{'charttime': '2149-05-26 09:26:00', 'label':...","[[[Fx surg nck humerus-clos, Emphysema NEC, Fx...","[{'drug': 'Hydromorphone', 'dose_val_rx': '2-6..."
4,10019,177759.0,"[{'charttime': '2163-05-14 19:53:00', 'label':...","[[[Septicemia NOS, Acute respiratry failure, A...","[{'drug': 'Propofol', 'dose_val_rx': '1000', '..."
...,...,...,...,...,...
124,44083,198330.0,"[{'charttime': '2112-05-28 12:30:00', 'label':...","[[[Pericardial disease NOS, Pleural effusion N...","[{'drug': 'Potassium Chloride', 'dose_val_rx':..."
125,44154,174245.0,"[{'charttime': '2178-05-14 16:45:00', 'label':...","[[[Septicemia NOS, nan, Food/vomit pneumonitis...","[{'drug': 'Pneumococcal Vac Polyvalent', 'dose..."
126,44212,163189.0,"[{'charttime': '2123-11-24 14:40:00', 'label':...","[[[Meth susc Staph aur sept, Septic shock, Ac ...","[{'drug': 'Sodium Chloride 0.9% Flush', 'dose..."
127,44222,192189.0,"[{'charttime': '2180-07-19 04:15:00', 'label':...","[[[Sinoatrial node dysfunct, Acute kidney fail...","[{'drug': 'Bisacodyl', 'dose_val_rx': '10', 'd..."
128,44228,103379.0,"[{'charttime': '2170-12-15 02:37:00', 'label':...","[[[E coli septicemia, Septic shock, Pneumonia,...","[{'drug': 'Influenza Virus Vaccine', 'dose_val..."

### - Diagnoses column looks nested
- This ensures diagnoses is a simple list like ["Sepsis", "Hypotension"] instead of [[["Sepsis", "Hypotension"]]].

In [53]:
diagnoses_grouped = (
    diagnoses.groupby(['subject_id','hadm_id'])['short_title']
    .apply(lambda x: list(x))
    .reset_index()
    .rename(columns={'short_title':'diagnoses'})
)

### NaN in prescriptions

## Final Dataset

In [56]:
final_dataset['prescriptions'] = final_dataset['prescriptions'].apply(
    lambda x: [] if isinstance(x, float) and pd.isna(x) else x
)
final_dataset

,subject_id,hadm_id,labs,diagnoses,prescriptions
0,10006,142345.0,"[{'charttime': '2164-10-23 17:33:00', 'label':...","[[[Sepsis, React-oth vasc dev/graft, nan, Hyp ...","[{'drug': 'Sodium Chloride 0.9% Flush', 'dose..."
1,10011,105331.0,"[{'charttime': '2126-08-15 01:30:00', 'label':...","[[[Acute necrosis of liver, Hpt B acte wo cm w...",[]
2,10013,165520.0,"[{'charttime': '2125-10-04 23:59:00', 'label':...","[[[Septicemia NOS, Subendo infarct, initial, C...","[{'drug': 'Furosemide', 'dose_val_rx': '20', '..."
3,10017,199207.0,"[{'charttime': '2149-05-26 09:26:00', 'label':...","[[[Fx surg nck humerus-clos, Emphysema NEC, Fx...","[{'drug': 'Hydromorphone', 'dose_val_rx': '2-6..."
4,10019,177759.0,"[{'charttime': '2163-05-14 19:53:00', 'label':...","[[[Septicemia NOS, Acute respiratry failure, A...","[{'drug': 'Propofol', 'dose_val_rx': '1000', '..."
...,...,...,...,...,...
124,44083,198330.0,"[{'charttime': '2112-05-28 12:30:00', 'label':...","[[[Pericardial disease NOS, Pleural effusion N...","[{'drug': 'Potassium Chloride', 'dose_val_rx':..."
125,44154,174245.0,"[{'charttime': '2178-05-14 16:45:00', 'label':...","[[[Septicemia NOS, nan, Food/vomit pneumonitis...","[{'drug': 'Pneumococcal Vac Polyvalent', 'dose..."
126,44212,163189.0,"[{'charttime': '2123-11-24 14:40:00', 'label':...","[[[Meth susc Staph aur sept, Septic shock, Ac ...","[{'drug': 'Sodium Chloride 0.9% Flush', 'dose..."
127,44222,192189.0,"[{'charttime': '2180-07-19 04:15:00', 'label':...","[[[Sinoatrial node dysfunct, Acute kidney fail...","[{'drug': 'Bisacodyl', 'dose_val_rx': '10', 'd..."
128,44228,103379.0,"[{'charttime': '2170-12-15 02:37:00', 'label':...","[[[E coli septicemia, Septic shock, Pneumonia,...","[{'drug': 'Influenza Virus Vaccine', 'dose_val..."

In [93]:
# Save as CSV
final_dataset.to_csv("data/processed/cleaned_diag_presc.csv", index=False)

In [94]:
import os
print(os.listdir("data/processed"))

['cleaned_diag_presc.csv']

In [59]:
import pandas as pd

admissions = pd.read_csv(r"C:\Users\SAKSHI PATIL\PycharmProjects\JupyterProject\data\raw\MediScan_database\ADMISSIONS.csv")[
    ['subject_id','hadm_id','admittime','dischtime','admission_type','diagnosis']
]

patients = pd.read_csv(r"C:\Users\SAKSHI PATIL\PycharmProjects\JupyterProject\data\raw\MediScan_database\PATIENTS.csv")[
    ['subject_id','gender','dob','dod']
]

In [64]:
admissions['admittime'] = pd.to_datetime(admissions['admittime'])
patients['dob'] = pd.to_datetime(patients['dob'])

In [65]:
admissions = admissions.merge(patients, on='subject_id', how='left')
admissions['age'] = (admissions['admittime'] - admissions['dob']).dt.days // 365

In [67]:
final_dataset = final_dataset.merge(
    admissions[['subject_id','hadm_id','admission_type','diagnosis','gender','age']],
    on=['subject_id','hadm_id'],
    how='left'
)
final_dataset

,subject_id,hadm_id,labs,diagnoses,prescriptions,admission_type_x,gender_x,age_x,admission_type_y,diagnosis_x,gender_y,age_y,admission_type,diagnosis_y,gender,age
0,10006,142345.0,"[{'charttime': '2164-10-23 17:33:00', 'label':...","[[[Sepsis, React-oth vasc dev/graft, nan, Hyp ...","[{'drug': 'Sodium Chloride 0.9% Flush', 'dose...",EMERGENCY,F,70,EMERGENCY,SEPSIS,F,70,EMERGENCY,SEPSIS,F,70
1,10011,105331.0,"[{'charttime': '2126-08-15 01:30:00', 'label':...","[[[Acute necrosis of liver, Hpt B acte wo cm w...",[],EMERGENCY,F,36,EMERGENCY,HEPATITIS B,F,36,EMERGENCY,HEPATITIS B,F,36
2,10013,165520.0,"[{'charttime': '2125-10-04 23:59:00', 'label':...","[[[Septicemia NOS, Subendo infarct, initial, C...","[{'drug': 'Furosemide', 'dose_val_rx': '20', '...",EMERGENCY,F,87,EMERGENCY,SEPSIS,F,87,EMERGENCY,SEPSIS,F,87
3,10017,199207.0,"[{'charttime': '2149-05-26 09:26:00', 'label':...","[[[Fx surg nck humerus-clos, Emphysema NEC, Fx...","[{'drug': 'Hydromorphone', 'dose_val_rx': '2-6...",EMERGENCY,F,73,EMERGENCY,HUMERAL FRACTURE,F,73,EMERGENCY,HUMERAL FRACTURE,F,73
4,10019,177759.0,"[{'charttime': '2163-05-14 19:53:00', 'label':...","[[[Septicemia NOS, Acute respiratry failure, A...","[{'drug': 'Propofol', 'dose_val_rx': '1000', '...",EMERGENCY,M,48,EMERGENCY,ALCOHOLIC HEPATITIS,M,48,EMERGENCY,ALCOHOLIC HEPATITIS,M,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,44083,198330.0,"[{'charttime': '2112-05-28 12:30:00', 'label':...","[[[Pericardial disease NOS, Pleural effusion N...","[{'drug': 'Potassium Chloride', 'dose_val_rx':...",EMERGENCY,M,54,EMERGENCY,PERICARDIAL EFFUSION,M,54,EMERGENCY,PERICARDIAL EFFUSION,M,54
125,44154,174245.0,"[{'charttime': '2178-05-14 16:45:00', 'label':...","[[[Septicemia NOS, nan, Food/vomit pneumonitis...","[{'drug': 'Pneumococcal Vac Polyvalent', 'dose...",EMERGENCY,M,300,EMERGENCY,ALTERED MENTAL STATUS,M,300,EMERGENCY,ALTERED MENTAL STATUS,M,300
126,44212,163189.0,"[{'charttime': '2123-11-24 14:40:00', 'label':...","[[[Meth susc Staph aur sept, Septic shock, Ac ...","[{'drug': 'Sodium Chloride 0.9% Flush', 'dose...",EMERGENCY,F,45,EMERGENCY,ACUTE RESPIRATORY DISTRESS SYNDROME;ACUTE RENA...,F,45,EMERGENCY,ACUTE RESPIRATORY DISTRESS SYNDROME;ACUTE RENA...,F,45
127,44222,192189.0,"[{'charttime': '2180-07-19 04:15:00', 'label':...","[[[Sinoatrial node dysfunct, Acute kidney fail...","[{'drug': 'Bisacodyl', 'dose_val_rx': '10', 'd...",EMERGENCY,M,73,EMERGENCY,BRADYCARDIA,M,73,EMERGENCY,BRADYCARDIA,M,73
128,44228,103379.0,"[{'charttime': '2170-12-15 02:37:00', 'label':...","[[[E coli septicemia, Septic shock, Pneumonia,...","[{'drug': 'Influenza Virus Vaccine', 'dose_val...",EMERGENCY,F,58,EMERGENCY,CHOLANGITIS,F,58,EMERGENCY,CHOLANGITIS,F,58

In [68]:
final_dataset = final_dataset.merge(
    admissions[['subject_id','hadm_id','admission_type','diagnosis','gender','age']],
    on=['subject_id','hadm_id'],
    how='left',
    suffixes=('', '_demo')   # add a suffix only to avoid clashes
)

In [70]:
print(final_dataset.columns)

Index(['subject_id', 'hadm_id', 'labs', 'diagnoses', 'prescriptions',
       'admission_type_x', 'gender_x', 'age_x', 'admission_type_y',
       'diagnosis_x', 'gender_y', 'age_y', 'admission_type', 'diagnosis_y',
       'gender', 'age', 'admission_type_demo', 'diagnosis', 'gender_demo',
       'age_demo'],
      dtype='str')

In [99]:
final_dataset.to_csv("data/interim/admissions_patients_stage.csv", index=False)

In [100]:
import os
print(os.listdir("data/interim"))

['admissions_patients_stage.csv', 'labs_clean.csv']

In [71]:
final_dataset = final_dataset.drop(
    columns=[col for col in final_dataset.columns if col.endswith('_x') or col.endswith('_y') or col.endswith('_demo')]
)

In [72]:
print(final_dataset.columns)

Index(['subject_id', 'hadm_id', 'labs', 'diagnoses', 'prescriptions',
       'admission_type', 'gender', 'age', 'diagnosis'],
      dtype='str')

In [101]:
# Save as CSV
final_dataset.to_csv("data/processed/final_dataset.csv", index=False)

import os
print(os.listdir("data/processed"))

['cleaned_diag_presc.csv', 'final_dataset.csv']

###  CHARTEVENTS

In [73]:
vitals = pd.read_csv(r"C:\Users\SAKSHI PATIL\PycharmProjects\JupyterProject\data\raw\MediScan_database\CHARTEVENTS.csv")[
    ['subject_id','hadm_id','itemid','charttime','valuenum','valueuom']
]

vitals_grouped = (
    vitals.groupby(['subject_id','hadm_id'])[['charttime','itemid','valuenum','valueuom']]
    .apply(lambda x: x.to_dict('records'))
    .reset_index()
    .rename(columns={0:'vitals'})
)

final_dataset = final_dataset.merge(vitals_grouped, on=['subject_id','hadm_id'], how='left')

C:\Users\SAKSHI PATIL\AppData\Local\Temp\ipykernel_23488\2273638266.py:1: DtypeWarning: Columns (0: value, 1: valueuom, 2: resultstatus, 3: stopped) have mixed types. Specify dtype option on import or set low_memory=False.
  vitals = pd.read_csv(r"C:\Users\SAKSHI PATIL\PycharmProjects\JupyterProject\data\raw\MediScan_database\CHARTEVENTS.csv")[

In [102]:
final_dataset.columns

Index(['subject_id', 'hadm_id', 'labs', 'diagnoses', 'prescriptions',
       'admission_type', 'gender', 'age', 'diagnosis', 'vitals',
       'report_text'],
      dtype='str')

In [109]:
# Save as CSV
final_dataset.to_csv("data/processed/final_dataset.csv", index=False)

import os

print(os.listdir("data/processed"))

['cleaned_diag_presc.csv', 'final_dataset.csv']

In [103]:
import numpy as np
import pandas as pd

def flatten_diagnoses(x):
    flat = []
    if isinstance(x, (list, np.ndarray)):
        for item in x:
            if isinstance(item, (list, np.ndarray)):
                for sub in item:
                    if pd.notna(sub):
                        flat.append(str(sub))
            elif pd.notna(item):
                flat.append(str(item))
    elif pd.notna(x):
        flat.append(str(x))
    return flat

final_dataset['diagnoses'] = final_dataset['diagnoses'].apply(flatten_diagnoses)

In [104]:
print(final_dataset['diagnoses'].head(5))

0    [Sepsis, React-oth vasc dev/graft, Hyp kid NOS...
1    [Acute necrosis of liver, Hpt B acte wo cm wo ...
2    [Septicemia NOS, Subendo infarct, initial, Car...
3    [Fx surg nck humerus-clos, Emphysema NEC, Fx f...
4    [Septicemia NOS, Acute respiratry failure, Acu...
Name: diagnoses, dtype: object

In [105]:
def generate_report(row):
    # Demographics
    demo_summary = f"Patient is a {row['age']}-year-old {row['gender']} admitted for {row['admission_type']}."

    # Labs
    abnormal_labs = [lab['label'] for lab in row['labs'] if isinstance(lab, dict) and lab.get('interpretation')=='abnormal']
    labs_summary = f"Abnormal labs: {', '.join(abnormal_labs)}." if abnormal_labs else "No abnormal labs."

    # Diagnoses
    diagnoses_summary = f"Diagnoses: {', '.join(row['diagnoses'])}." if row['diagnoses'] else "No diagnoses recorded."

    # Prescriptions
    prescriptions_summary = (
        f"Prescriptions: {', '.join([p['drug'] for p in row['prescriptions'] if isinstance(p, dict)])}."
        if row['prescriptions'] else "No prescriptions recorded."
    )

    # Vitals
    vitals_summary = (
        f"Vitals recorded: {len(row['vitals'])} entries." if isinstance(row['vitals'], list) else "No vitals recorded."
    )

    return f"{demo_summary} {labs_summary} {diagnoses_summary} {prescriptions_summary} {vitals_summary}"

In [106]:
final_dataset['report_text'] = final_dataset.apply(generate_report, axis=1)

In [107]:
print(final_dataset[['subject_id','hadm_id','report_text']].head(1))

   subject_id   hadm_id                                        report_text
0       10006  142345.0  Patient is a 70-year-old F admitted for EMERGE...

In [133]:
import numpy as np
import json

def deep_clean(obj):
    if isinstance(obj, dict):
        return {k: deep_clean(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [deep_clean(v) for v in obj]
    elif obj is None or (isinstance(obj, float) and np.isnan(obj)):
        return None
    else:
        return obj

In [134]:
for col in ["labs", "diagnoses", "prescriptions", "vitals"]:
    final_dataset[col] = final_dataset[col].apply(
        lambda x: json.dumps(deep_clean(x)) if isinstance(x, (dict, list)) else x
    )

In [136]:
print(final_dataset[["labs","vitals"]].head(3))

                                                labs  \
0  [{"charttime": "2164-10-23 17:33:00", "label":...
1  [{"charttime": "2126-08-15 01:30:00", "label":...
2  [{"charttime": "2125-10-04 23:59:00", "label":...

                                              vitals
0  [{"charttime": "2164-10-23 21:10:00", "itemid"...
1  [{"charttime": "2126-08-14 21:00:00", "itemid"...
2  [{"charttime": "2125-10-04 22:55:00", "itemid"...

In [122]:
# Save as CSV
final_dataset.to_csv("data/processed/final_main_dataset.csv", index=False)

import os
print(os.listdir("data/processed"))

['cleaned_diag_presc.csv', 'final_dataset.csv', 'final_main_dataset.csv']

In [113]:
import sqlalchemy
print(sqlalchemy.__version__)

2.0.48

In [115]:
from sqlalchemy import create_engine
engine = create_engine("postgresql://postgres:Sak%408788@localhost:5432/mediscan")

In [140]:
final_dataset[["subject_id","hadm_id","admission_type","gender","age","diagnosis","report_text"]] \
    .to_sql("final_dataset", engine, if_exists="append", index=False)

129